# Site settings
title: Cheng Wan
description: AI for Medicine, Computer Vision and Multimodal. Cornell ECE Ph.D. Student.
url: https://jornywan.github.io
baseurl: ""

# Author settings
author:
  name: Cheng Wan
  email: jouiney666@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:year/:month/:day/:title/

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md
  - LICENSE
  - CONTRIBUTING.md
  - FAQ.md
  - INSTALL.md
  - CUSTOMIZE.md
  - docker-compose.yml
  - docker-compose-slim.yml
  - Dockerfile
  - package.json
  - package-lock.json
  - purgecss.config.js

# Collections
collections:
  news:
    output: false

# Defaults
defaults:
  - scope:
      path: ""
      type: "news"
    values:
      layout: "news"
